version: '3'
services:
  app:
    build:
      context: ./app
    ports:
      - 8080
    depends_on:
      - db
    

  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: radhey
      POSTGRES_PASSWORD: radhey
      POSTGRES_DB: projectdb

